### 课程信息查询接口测试
POST {{content_host}}/content/course/list?pageNo=2&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

### 课程分类查询接口测试
GET {{content_host}}/content/course-category/tree-nodes

### 新增课程接口测试
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 100,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "dsa",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "dsada",
  "grade": "204001",
  "description": "hyx测试课程hyx测试课程hyx测试课程"
}

### 根据课程Id查询课程基本信息接口测试
GET {{content_host}}/content/course/39

### 根据课程Id查询课程计划接口测试
GET {{content_host}}/content/teachplan/117/tree-nodes

### 新增课程计划--章
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 0,
  "grade" : 1,
  "pname" : "新章名称 [点击修改]"
}

### 删除课程计划
DELETE {{content_host}}/content/teachplan/43

### 查询课程教师信息
GET {{content_host}}/content/courseTeacher/list/74